CREATE TABLE `channel` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(200),
  `create_user_id` INTEGER UNSIGNED NOT NULL,
  `create_time` DATETIME NOT NULL,
  `status` INTEGER UNSIGNED NOT NULL,
  `is_store` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `end_time` DATETIME,
  `output_type` INTEGER UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

CREATE TABLE `store_message` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INTEGER UNSIGNED NOT NULL,
  `channel_id` INTEGER UNSIGNED NOT NULL,
  `content` VARCHAR(300) NOT NULL,
  `send_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

CREATE TABLE `user_channel_relation` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `userId` INTEGER UNSIGNED NOT NULL,
  `channelId` INTEGER UNSIGNED NOT NULL,
  `status` INTEGER UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

CREATE TABLE `user` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `from_user_name` VARCHAR(20) NOT NULL,
  `fake_id` VARCHAR(45),
  `nickName` VARCHAR(45),
  `remarkName` VARCHAR(45),
  `groupId` INTEGER UNSIGNED,
  `lastAccessedTime` DATETIME NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;
